group component initial changes
gctools-outilsgc/gccollab-frontend pull request #118
Opened 2023-08-02 19:40 UTC by AdiMakkar

closes #77

2023-08-02 19:41 UTC, AdiMakkar commented
requires changes for: 
1. model
2. [routerLink] 

in group-card.component.html

Additionally to remove comment from the InterceptorGuard before merging

2023-08-08 15:11 UTC, doug0102 requested changes

2023-08-08 15:11 UTC, doug0102 commented on src/app/features/groups/components/group-card/group-card.component.ts
> +import { TooltipDirection } from 'src/app/shared/models/tooltip-direction';
I don't think we'll be needing tooltips for this component. You can remove this.

2023-08-08 15:11 UTC, doug0102 commented on src/app/features/groups/components/group-card/group-card.component.ts
> +   tooltipDirection = TooltipDirection;
I don't think we'll be needing tooltips for this component. You can remove this.

2023-08-08 15:11 UTC, doug0102 commented on src/app/features/groups/components/group-card/group-card.component.ts
> +   groupStatus: string = 'Open';
This isn't used so you can remove it.

2023-08-08 15:11 UTC, doug0102 commented on src/app/features/groups/components/group-card/group-card.component.ts
> +   materialButtonType = MaterialButtonType;
This isn't used so you can remove it.

2023-08-08 15:11 UTC, doug0102 commented on src/app/core/services/group.service.ts
> +            //Open,
Replace with

`GroupStatus.Open,
            GroupStatus.Closed`

2023-08-08 15:11 UTC, doug0102 commented on src/app/features/groups/components/group-card/group-card.component.ts
> +   onMouseOver() {
For the onMouseOver and onMouseOut stuff, is this just to underline text? You can use pure CSS for this using [:hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) on your selector. I would recommend this way as it's less code.

2023-08-15 17:55 UTC, doug0102 approved these changes

2023-08-15 17:59 UTC, merged