Event page
gctools-outilsgc/gccollab-frontend pull request #197
Opened 2024-01-04 20:20 UTC by AdiMakkar

closes #110

2024-01-04 20:29 UTC, doug0102 commented
Also check that the test is passing. I suspect that it will fail right now since I didn't see any changes in the file. You will need to add the stuff for the translations to work as well as that FormControl pipe. You can see an example of that in `event-form.component.spec.ts`

2024-01-04 20:31 UTC, doug0102 requested changes
See my comment about the test file. I think you will need to double check that the test is passing. An example of what you will probably need to add can be found in `event-form.component.spec.ts`

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  @Input() editing: boolean = false;
I don't think this is used in this component so you can delete it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  events: Event[] = [];
Not used so you can remove it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  eventsPage: number = 1;
Not used you can remove it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  loadingEvents: boolean = true;
Not used you can remove it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  materialButtonType = MaterialButtonType;
Also not used so you can remove it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +import { MaterialButtonType } from 'src/app/shared/models/material-button-type';
Remove this since we aren't using it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  declineEvent() {
This method is never used so you can remove it.

2024-01-04 20:31 UTC, doug0102 commented on src/app/features/events/events.component.ts
> +  confirmEvent() {
This method is never used so you can remove it.

2024-01-10 05:42 UTC, AdiMakkar commented
Requested changes made. Tests updated for Translations and FormControl.

2024-01-10 14:35 UTC, doug0102 submitted a review, later dismissed

2024-01-10 17:30 UTC, AdiMakkar commented on src/app/features/events/events.component.html
> +                orientation="grid"
Orientation switched to horizontal.

2024-01-10 18:33 UTC, doug0102 approved these changes

2024-01-10 18:34 UTC, merged